
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import bean.Animal;
import bean.Bird;
import bean.Chicken;

@RunWith(SpringRunner.class)
@SpringBootTest(classes = Animal.class)
public class LibraryTest {
	@Autowired
	private Animal a;

	@Autowired
	private Bird b;

	@Autowired
	private Chicken c;

	@Test
	public void testSpringBoot() {
		System.out.println(a);
		System.out.println(b);
		System.out.println(c);
	}
}
